from tkinter import*
from tkinter import messagebox
w=Tk()
w.geometry('700x400')
w.title('Carnival')
def Submit():
    messagebox.showinfo("Info","Thankyou for Registering!")
l1=Label(w,text="Name:").grid(row=1,column=3)
l1=Label(w,text="Registered no.").grid(row=2,column=3)
l1=Label(w,text="Email:").grid(row=3,column=3)
l1=Label(w,text="Branch:").grid(row=4,column=3)
r=Radiobutton(w,text="EEE").grid(row=4,column=4)
r=Radiobutton(w,text="ECE").grid(row=5,column=4)
r=Radiobutton(w,text="CSE").grid(row=6,column=4)
r=Radiobutton(w,text="CSM").grid(row=7,column=4)
r=Radiobutton(w,text="CSO").grid(row=8,column=4)
r=Radiobutton(w,text="Mech").grid(row=9,column=4)
l1=Label(w,text="Section").grid(row=3,column=3)
e=Entry(w,width=30).grid(row=1,column=4)
e1=Entry(w,width=30).grid(row=2,column=4)
e3=Entry(w,width=30).grid(row=3,column=4)
e4=Entry(w,width=30).grid(row=2,column=4)
b=Button(w,text='Submit',fg="Green",command=Submit).grid(row=10,column=5)
b1=Button(w,text='Cancel',command=quit).grid(row=10,column=4)
w.mainloop()
